version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ed:36:c7:0e:10:9e:83:74:68:d9:fc:c1:73:e6:05:1b"
      - checkout
      - run: echo "$CIRCLE_WORKFLOW_ID"
      - run: . ./pipeline_cci.sh
workflows:
  nightly:
    jobs:
      - build