version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          command: |
            source ~/.circlerc
            pyenv install $PYTHON_VERSION
      - run:      
            cat ~/.pyenv/versions