version: 2.1

jobs:
  build-and-test:
    executor:
      name: node/default
    resource_class: large
    steps:
      - node/install:
          install-yarn: true
          node-version: "11.14.0"
          yarn-version: "1.22.5"
      - echo: "If you are reading this, then here we are."