version: 2.1

jobs:
  build:
    parameters:
      first-step:
        type: string
        default: "first step"
    docker: 
      - image: cimg/node
    steps:
      - add_ssh_keys
      - run: echo This is my << parameters.first-step >>
      - echo: "this is my second step"
      - store_artifacts:
          path: test-results
          destination: results

  deploy:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - add_ssh_keys
      - run:
          name: Always run
          command: echo "This should always run"
          when: on_fail

workflows:
  build-and-deploy:
    jobs:
      - build:
          pre-steps:
            - run:
                command: |
                  mkdir test-results
                  cd test-results
                  touch results.json
                  echo results_not_found >> results.json
          filters:
            branches:
              ignore: test-branch
      - deploy:
          requires:
            - build