version: 2
jobs:
  foo:
    docker:
      - image: circleci/node:1.11.12-buster
    steps:
      - checkout
      - run: echo "Hello, Buster"
  bar:
    docker:
      - image: circleci/node:1.11.12-buster
    steps:
      - checkout
      - run: echo "Howdy, Buster"
      - run:
          name: Print the Current Time
          command: date
workflows:
  version: 2
  build_and_test:
    jobs:
      - foo
      - bar