version: 2.1
jobs:
  docker:
    working_directory: /opt/build
    docker:
      - image: alpine:3.9
        environment:
          ECR_REPOSITORY: <repository>
    steps:
      - run:
        name: Install system dependencies
        command: |
          apk add -U git curl openssh tar gzip python3
          pip3 install awscli
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      - run:
        name: Install Docker client
        command: |
          VER="19.03.8"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz