version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/openjdk:jdk-node-browsers
    working_directory: /tmp

jobs:
  install:
    executor: my-executor

    steps:
      - checkout:
          path: workspace
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "workspace/yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run:
          name: Nodejs Version
          command: node --version
      - run:
          name: Install Packages
          command: cd workspace && yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "workspace/yarn.lock" }}
          paths:
            - facebook-www
            - node_modules
      - persist_to_workspace:
          root: workspace
          paths:
            - .

  lint:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Lint
          command: cd workspace && yarn lint
      - run:
          name: Check Prettier
          command: cd workspace && yarn lightyear:prettier-check

  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Test
          command: cd workspace && yarn test --maxWorkers=2

  test-prod:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Test Prod
          command: cd workspace && yarn test-prod --maxWorkers=2

  build:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Check that build succeeds
          command: cd workspace && yarn lightyear:build

workflows:
  validate:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - test-prod:
          requires:
            - install
      - build:
          requires:
            - install