version: 2
machine:
    image: windows-server-2019-vs2019:edge
    steps:
      - checkout
      - run: echo "Hello, Edge Machine"
      - run:
          name: Print the Current Time
          command: date
  