version: 2.1

jobs:
  testing:
    docker: 
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: test
          command: |
            docker-compose run tester

workflows:
  networktest:
    jobs:
      - testing