version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: sudo npm install -g react-native-cli
            - run: sudo npm install -g detox-cli
            - run: sudo npm install -g expo-cli
            - run: npx expo login -u $EXPO_LOGIN -p $EXPO_PWD
            - run: npx expo publish --non-interactive --max-workers 1 --release-channel dev
workflows:
    build-and-release:
      jobs:
        - build-and-release