version: 2
jobs:
  build:
    docker:
    - image: circleci/python:latest
      environment:
        CIRCLE_TEST_REPORTS: test
        TESTOPTS: --ci-dir=${CIRCLE_TEST_REPORTS}/reports
    steps:
    - checkout
    - restore_cache:
        keys: v1-dep-{{ arch }}
    - run: echo $CIRCLE_TEST_REPORTS
    - run: echo $TESTOPTS
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Just another test