version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2021.08.1
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD       
    steps:
      - checkout
      - run : printenv 
  test:
    docker:
      - image: cimg/python:3.7-node
    steps:
      - checkout
      - run: python --version
      - run: node --version     
      - run : echo "Hello World! Just Another Test Job"   
    
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
