version: 2
jobs:
  build:
    macos:
      xcode: 11.1.0
    steps:
    - checkout
    - attach_workspace:
        at: ~/project
    - run:
        name: Install XCHTMLReport
        command: |
          brew unlink xchtmlreport
          brew install --HEAD https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/xchtmlreport.rb
    - run:
        name: Adding XCHTMLReport to Fastlane
        command: fastlane add_plugin xchtmlreport
    - persist_to_workspace:
        root: ~/project
        paths:
        - .
workflows:
  all_the_things:
    jobs:
    - build
  version: 2