version: 2
jobs:
  foo:
    machine:
    - image: circleci/ruby:latest
    - resource_class: large
    parallelism: 2
    steps:
      - checkout
      - run: echo "Hello, Ruby Latest Image"
  bar:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Hello, Buster"
      - run:
          name: Print the Current Time
          command: date
workflows:
  version: 2
  build_and_test:
    jobs:
      - foo
      - bar