version: 2

jobs:
  run_tests:
    docker:
    - image: circleci/ruby:2.4.9-node-browsers
    steps:
      - checkout
      - run: echo "Running tests"

workflows:
  version: 2
  build:
    jobs:
      - run_tests