version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          command: |
            source ~/.circlerc
            pyenv install 3.7.2
      - run:      
           pyenv versions

      - slack/status:
          mention: "@jonathan"
          message: "Your build did a thing!"
          color: "#42e2f4"
       