version: 2.1
jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
    steps:
    - checkout
    - run:
        command: choco install wixtoolset
    resource_class: windows.medium
    shell: powershell.exe -ExecutionPolicy Bypass
workflows:
  Just a workflow:
    jobs:
    - build