version: 2.1
workflows:
  btd:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:stable
      - image: ratelimitalways/test
    steps:
      - run:
          name: Show storage prefix
          command: cat /.circleci-runner-config.json  | jq .Dispatched.TaskInfo.Storage