version: 2


job-defaults: &job-defaults
  docker:
    - image: alpine
  steps:
    - run: echo "task A"
    - run: echo "task B"

jobs:

  build:
    <<: *job-defaults
    steps:
      - run: echo "task C"
