version: 2.1
jobs:
  build:
    docker:
    - image: circleci/python:3.6.1
    steps:
    - run:
        name: Test
        command: |
          sudo pip install pipenv
          pipenv install flake8 --skip-lock
workflows:
  build-and-deploy:
    jobs:
    - build